# experiment config
seed      : 0
gpu       : 2
data_dir  : './dataset'

# model config
dataset       : 'MNIST'
model_name    : 'MnistBaseNet'
bat_size      : 128
n_epoch       : 10
learning_rate : 1.0